export interface Song {
  id: string;
  title: string;
  imageUrl?: string;
  audioUrl: string;
  createdAt: Date;
  updatedAt: Date;
  uploadedBy?: string;
  artist?: string;
  album?: string;
  description?: string;
  genre: string[];
  lyrics?: string;
  durationSeconds: number;
}

export const MUSIC_TYPES: string[] = [
  // Moods
  "Happy",
  "Sad",
  "Relaxing",
  "Energetic",
  "Romantic",
  "Melancholic",
  "Chill",
  "Uplifting",
  "Dark",
  "Epic",
  "Calm",
  "Motivational",
  "Mysterious",
  "Groovy",
  "Euphoric",
  "Peaceful",
  "Aggressive",
  "Nostalgic",
  "Dreamy",
  "Somber",
  "Soulful",
  "Reflective",
  "Playful",
  "Hypnotic",
  "Sensual",

  // Genres
  "Pop",
  "Rock",
  "Hip-Hop",
  "R&B",
  "Jazz",
  "Blues",
  "Classical",
  "Electronic",
  "House",
  "Techno",
  "Trance",
  "Reggae",
  "Salsa",
  "Country",
  "Folk",
  "Metal",
  "Punk",
  "Indie",
  "Alternative",
  "Funk",
  "Soul",
  "Gospel",
  "Ambient",
  "Lo-Fi",
  "Soundtrack",
] as const;

const getTestImage = () => {
  return `https://picsum.photos/id/${Math.floor(
    Math.random() * 300
  )}/2000/2000`;
};

const audioFiles = [
  "/songs/DRAKE-NOKIA.mp3",
  "/songs/KENDRICKLAMAR-NOTLIKEUS.mp3",
  "/songs/Pitbull-Time Of Our Lives.mp3",
  "/songs/Lil Wayne-Mirror ft. Bruno Mars.mp3",
  "/songs/PARTYNEXTDOOR & DRAKE - SOMEBODY LOVES ME.mp3",
  "/songs/50 Cent - In Da Club (Official Music Video).mp3",
  "/songs/Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song).mp3",
  "/songs/Kanye West - Runaway (Extended Video Version) ft. Pusha T.mp3",
  "/songs/Taylor Swift - You Belong With Me.mp3",
  "/songs/Farruko - Pepas (Official Video).mp3",
  "/songs/Chief Keef - Love Sosa.mp3",
  "/songs/Rihanna - We Found Love ft. Calvin Harris.mp3",
];

export const songs: Song[] = [
  {
    id: "1",
    title: "NOKIA",
    imageUrl: getTestImage(),
    audioUrl: audioFiles[0],
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "Drake",
    artist: "Drake",
    album: "",
    description: "Description of NOKIA",
    genre: ["Rap", "Pop"],
    lyrics: "Lyrics for NOKIA",
    durationSeconds: 265,
  },
  {
    id: "2",
    title: "Not Like Us",
    imageUrl: getTestImage(),
    audioUrl: audioFiles[1],
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "Kendrick Lamar",
    artist: "Kendrick Lamar",
    album: "",
    description: "This is a description of Not Like US.",
    genre: ["Rap", "Pop"],
    lyrics: "Lyrics for Not Like Us",
    durationSeconds: 273,
  },
  {
    id: "3",
    title: "Time Of Our Lives",
    imageUrl: getTestImage(),
    audioUrl: audioFiles[2],
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "Pitbull",
    artist: "Pitbull",
    album: "",
    description: "This is a description of Time Of Our Lives.",
    genre: ["Pop", "Dance"],
    lyrics: "Lyrics for Time Of Our Lives",
    durationSeconds: 281,
  },
  {
    id: "4",
    title: "Mirror",
    imageUrl: getTestImage(),
    audioUrl: audioFiles[3],
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "Lil Wayne",
    artist: "Lil Wayne",
    album: "",
    description: "This is a description of Mirror.",
    genre: ["Classical"],
    lyrics: "Lyrics for Mirror",
    durationSeconds: 242,
  },
  {
    id: "5",
    title: "Somebody Loves Me",
    imageUrl: getTestImage(),
    audioUrl: audioFiles[4],
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "PARTYNEXTDOOR",
    artist: "PARTYNEXTDOOR",
    album: "",
    description: "This is a description of Somebody Loves Me.",
    genre: ["Pop"],
    lyrics: "Lyrics for Somebody Loves Me",
    durationSeconds: 182,
  },
  {
    id: "6",
    title: "In Da Club",
    imageUrl: getTestImage(),
    audioUrl: audioFiles[5],
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "50 Cent",
    artist: "50 Cent",
    album: "",
    description: "This is a description of In Da Club.",
    genre: ["Hip-Hop", "Rap"],
    lyrics: "Lyrics for In Da Club",
    durationSeconds: 247,
  },
  {
    id: "7",
    title: "Waka Waka",
    imageUrl: getTestImage(),
    audioUrl: audioFiles[6],
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "Shakira",
    artist: "Shakira",
    album: "",
    description: "This is a description of Waka Waka.",
    genre: ["Pop", "Dance"],
    lyrics: "Lyrics for Waka Waka",
    durationSeconds: 210,
  },
  {
    id: "8",
    title: "Runaway",
    imageUrl: getTestImage(),
    audioUrl: audioFiles[7],
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "Kanye West",
    artist: "Kanye West",
    album: "",
    description: "This is a description of Runaway.",
    genre: ["Country"],
    lyrics: "Lyrics for Runaway",
    durationSeconds: 408,
  },
  {
    id: "9",
    title: "You Belong With Me",
    imageUrl: getTestImage(),
    audioUrl: audioFiles[8],
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "Taylor Swift",
    artist: "Taylor Swift",
    album: "",
    description: "This is a description of You Belong With Me.",
    genre: ["Pop"],
    lyrics: "Lyrics for You Belong With Me",
    durationSeconds: 228,
  },
  {
    id: "10",
    title: "Pepas",
    imageUrl: getTestImage(),
    audioUrl: audioFiles[9],
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "Farruko",
    artist: "Farruko",
    album: "",
    description: "This is a description of Pepas.",
    genre: ["Pop", "Dance"],
    lyrics: "Lyrics for Pepas",
    durationSeconds: 293,
  },
  {
    id: "11",
    title: "Love Sosa",
    imageUrl: getTestImage(),
    audioUrl: audioFiles[10],
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "Chief Keef",
    artist: "Chief Keef",
    album: "",
    description: "This is a description of Love Sosa.",
    genre: ["Rap", "Hip-Hop"],
    lyrics: "Lyrics for Love Sosa",
    durationSeconds: 218,
  },
  {
    id: "12",
    title: "We Found Love",
    imageUrl: getTestImage(),
    audioUrl: audioFiles[11],
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "Rihanna",
    artist: "Rihanna",
    album: "",
    description: "This is a description of We Found Love.",
    genre: ["Pop", "Dance"],
    lyrics: "Lyrics for We Found Love",
    durationSeconds: 276,
  },
];
