export interface Song {
  id: string;
  title: string;
  imageUrl?: string;
  audioUrl: string;
  createdAt: Date;
  updatedAt: Date;
  uploadedBy?: string;
  artist?: string;
  album?: string;
  description?: string;
  genre: string[];
  lyrics?: string;
  durationSeconds: number;
}

const getTestImage = () => {
  return `https://picsum.photos/id/${Math.floor(
    Math.random() * 300
  )}/2000/2000`;
};
const testAudio = "sample.mp3";

export const songs: Song[] = [
  {
    id: "1",
    title: "Song One",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User1",
    artist: "Artist1",
    album: "Album1",
    description: "This is a description of Song One.",
    genre: ["Pop", "Dance"],
    lyrics: "Lyrics for Song One",
    durationSeconds: 180,
  },
  {
    id: "2",
    title: "Song Two",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User2",
    artist: "Artist2",
    album: "Album2",
    description: "This is a description of Song Two.",
    genre: ["Rock", "Indie"],
    lyrics: "Lyrics for Song Two",
    durationSeconds: 240,
  },
  {
    id: "3",
    title: "Song Three",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User3",
    artist: "Artist3",
    album: "Album3",
    description: "This is a description of Song Three.",
    genre: ["Jazz"],
    lyrics: "Lyrics for Song Three",
    durationSeconds: 300,
  },
  {
    id: "4",
    title: "Song Four",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User4",
    artist: "Artist4",
    album: "Album4",
    description: "This is a description of Song Four.",
    genre: ["Classical"],
    lyrics: "Lyrics for Song Four",
    durationSeconds: 180,
  },
  {
    id: "5",
    title: "Song Five",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User5",
    artist: "Artist5",
    album: "Album5",
    description: "This is a description of Song Five.",
    genre: ["Pop"],
    lyrics: "Lyrics for Song Five",
    durationSeconds: 240,
  },
  {
    id: "6",
    title: "Song Six",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User6",
    artist: "Artist6",
    album: "Album6",
    description: "This is a description of Song Six.",
    genre: ["Rock"],
    lyrics: "Lyrics for Song Six",
    durationSeconds: 300,
  },
  {
    id: "7",
    title: "Song Seven",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User7",
    artist: "Artist7",
    album: "Album7",
    description: "This is a description of Song Seven.",
    genre: ["Hip-Hop", "Rap"],
    lyrics: "Lyrics for Song Seven",
    durationSeconds: 180,
  },
  {
    id: "8",
    title: "Song Eight",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User8",
    artist: "Artist8",
    album: "Album8",
    description: "This is a description of Song Eight.",
    genre: ["Country"],
    lyrics: "Lyrics for Song Eight",
    durationSeconds: 240,
  },
  {
    id: "9",
    title: "Song Nine",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User9",
    artist: "Artist9",
    album: "Album9",
    description: "This is a description of Song Nine.",
    genre: ["Pop", "R&B"],
    lyrics: "Lyrics for Song Nine",
    durationSeconds: 300,
  },
  {
    id: "10",
    title: "Song Ten",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User10",
    artist: "Artist10",
    album: "Album10",
    description: "This is a description of Song Ten.",
    genre: ["Electronic"],
    lyrics: "Lyrics for Song Ten",
    durationSeconds: 180,
  },
  {
    id: "11",
    title: "Song Eleven",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User11",
    artist: "Artist11",
    album: "Album11",
    description: "This is a description of Song Eleven.",
    genre: ["Folk"],
    lyrics: "Lyrics for Song Eleven",
    durationSeconds: 120,
  },
  {
    id: "12",
    title: "Song Twelve",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User12",
    artist: "Artist12",
    album: "Album12",
    description: "This is a description of Song Twelve.",
    genre: ["Indie", "Alternative"],
    lyrics: "Lyrics for Song Twelve",
    durationSeconds: 240,
  },
  {
    id: "13",
    title: "Song Thirteen",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User13",
    artist: "Artist13",
    album: "Album13",
    description: "This is a description of Song Thirteen.",
    genre: ["Reggae"],
    lyrics: "Lyrics for Song Thirteen",
    durationSeconds: 180,
  },
  {
    id: "14",
    title: "Song Fourteen",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User14",
    artist: "Artist14",
    album: "Album14",
    description: "This is a description of Song Fourteen.",
    genre: ["Blues"],
    lyrics: "Lyrics for Song Fourteen",
    durationSeconds: 300,
  },
  {
    id: "15",
    title: "Song Fifteen",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User15",
    artist: "Artist15",
    album: "Album15",
    description: "This is a description of Song Fifteen.",
    genre: ["Classical"],
    lyrics: "Lyrics for Song Fifteen",
    durationSeconds: 300,
  },
  {
    id: "16",
    title: "Song Sixteen",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User16",
    artist: "Artist16",
    album: "Album16",
    description: "This is a description of Song Sixteen.",
    genre: ["Rock", "Alternative"],
    lyrics: "Lyrics for Song Sixteen",
    durationSeconds: 300,
  },
  {
    id: "17",
    title: "Song Seventeen",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User17",
    artist: "Artist17",
    album: "Album17",
    description: "This is a description of Song Seventeen.",
    genre: ["Dance", "Pop"],
    lyrics: "Lyrics for Song Seventeen",
    durationSeconds: 300,
  },
  {
    id: "18",
    title: "Song Eighteen",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User18",
    artist: "Artist18",
    album: "Album18",
    description: "This is a description of Song Eighteen.",
    genre: ["Pop"],
    lyrics: "Lyrics for Song Eighteen",
    durationSeconds: 300,
  },
  {
    id: "19",
    title: "Song Nineteen",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User19",
    artist: "Artist19",
    album: "Album19",
    description: "This is a description of Song Nineteen.",
    genre: ["Soul"],
    lyrics: "Lyrics for Song Nineteen",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
  {
    id: "20",
    title: "Song Twenty",
    imageUrl: getTestImage(),
    audioUrl: testAudio,
    createdAt: new Date(),
    updatedAt: new Date(),
    uploadedBy: "User20",
    artist: "Artist20",
    album: "Album20",
    description: "This is a description of Song Twenty.",
    genre: ["Hip-Hop"],
    lyrics: "Lyrics for Song Twenty",
    durationSeconds: 300,
  },
];
